"""Auto-generated by demos/BeH2/BeH2.py.

supernet-searched ansatz that prepares the BeH2 active-space ground state.
Regenerate with: ``python -m demos.BeH2.BeH2``.
Plot with:       ``python -m demos.BeH2.BeH2_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, cx, hadamard, rx, ry, rz, rzz
from aicir.visual import plot


def build_beh2_npu_qas_circuit():
    """Return the supernet-searched BeH2 ground-state circuit."""
    gates = [
        rz(0.6125152707099915, 0),
        hadamard(2),
        rx(1.577965259552002, 3),
        hadamard(4),
        rx(-1.7932054106495343e-05, 5),
        hadamard(6),
        hadamard(7),
        rx(-0.000613112177234143, 8),
        rz(0.5972568988800049, 9),
        hadamard(10),
        hadamard(11),
        hadamard(12),
        rx(-0.776731550693512, 13),
        rz(1.1374813318252563, 14),
        rz(1.1227080821990967, 15),
        cx(1, [0]),
        rzz(-0.0050341468304395676, 4, 5),
        cx(6, [5]),
        rzz(-1.5707974433898926, 7, 8),
        cx(9, [8]),
        rzz(1.5707550048828125, 9, 10),
        cx(12, [11]),
        cx(13, [12]),
        cx(14, [13]),
        cx(15, [14]),
        rx(-0.12772148847579956, 0),
        hadamard(2),
        rz(1.5667171478271484, 3),
        ry(0.007374930195510387, 4),
        ry(0.7741317749023438, 6),
        rx(-0.9504817724227905, 7),
        ry(1.570788860321045, 8),
        rz(0.8583611249923706, 9),
        rx(1.5707980394363403, 10),
        rx(2.2804739475250244, 11),
        hadamard(12),
        rx(0.7661446928977966, 13),
        rz(1.2724252939224243, 14),
        ry(-1.5709084272384644, 15),
        rzz(-0.2393902838230133, 0, 1),
        cx(4, [3]),
        cx(6, [5]),
        cx(8, [7]),
        cx(10, [9]),
        cx(11, [10]),
        rzz(-0.00029751763213425875, 14, 15),
        rx(0.07479144632816315, 0),
        rz(0.9421477317810059, 1),
        ry(3.687424339204881e-07, 2),
        rz(0.35929420590400696, 4),
        hadamard(5),
        ry(0.796676516532898, 6),
        rx(-0.6203106641769409, 7),
        ry(7.4299996413174085e-06, 8),
        rx(2.1652151644957485e-06, 9),
        hadamard(10),
        rz(-0.7940457463264465, 12),
        ry(-1.3658623174706008e-06, 14),
        hadamard(15),
        rzz(-0.23487164080142975, 0, 1),
        cx(2, [1]),
        cx(3, [2]),
        rzz(0.698533833026886, 4, 5),
        rzz(-0.7932179570198059, 5, 6),
        cx(7, [6]),
        rzz(6.467509479080036e-07, 7, 8),
        cx(10, [9]),
        rzz(-0.04793316498398781, 10, 11),
        cx(13, [12]),
        rx(0.08904188871383667, 0),
        ry(-0.04727477207779884, 1),
        rx(-8.238136217642023e-08, 2),
        hadamard(3),
        rz(0.33924463391304016, 4),
        rz(-2.3590168952941895, 5),
        hadamard(8),
        ry(1.4524881635225029e-06, 9),
        hadamard(10),
        ry(1.5706843137741089, 11),
        ry(-1.570852279663086, 12),
        rx(0.8046544790267944, 13),
        rz(-0.29298874735832214, 15),
        rzz(-0.8746966123580933, 1, 2),
        rzz(0.3055545687675476, 2, 3),
        cx(5, [4]),
        rzz(0.30808743834495544, 6, 7),
        rzz(1.3172410726547241, 7, 8),
        cx(9, [8]),
        cx(10, [9]),
        cx(11, [10]),
        rzz(-7.73675856180489e-06, 11, 12),
        rzz(1.5714839696884155, 13, 14),
        cx(15, [14]),
    ]
    return Circuit(*gates, n_qubits=16)


circuit = build_beh2_npu_qas_circuit()
circuit.plot()

if __name__ == "__main__":
    figure_path = Path(__file__).with_name("BeH2_cir.png")
    plot(circuit, figure_path, title='BeH2 supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
