"""Auto-generated by demos/BeH2/BeH2.py.

supernet-searched ansatz that prepares the BeH2 active-space ground state.
Regenerate with: ``python -m demos.BeH2.BeH2``.
Plot with:       ``python -m demos.BeH2.BeH2_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, double_excitation, pauli_x, single_excitation
from aicir.visual import plot


def build_beh2_npu_qas_circuit():
    """Return the supernet-searched BeH2 ground-state circuit."""
    gates = [
        pauli_x(5),
        pauli_x(6),
        pauli_x(7),
        pauli_x(13),
        pauli_x(14),
        pauli_x(15),
        single_excitation(-0.017562903463840485, 4, 7),
        single_excitation(-0.014571094885468483, 3, 7),
        single_excitation(0.00010433580609969795, 10, 15),
        single_excitation(0.00010919659689534456, 2, 7),
        single_excitation(-0.037401486188173294, 9, 15),
        single_excitation(-0.5735098719596863, 4, 6),
        single_excitation(-0.02497892826795578, 11, 14),
        single_excitation(-0.04160556569695473, 3, 6),
        single_excitation(0.01418783888220787, 1, 6),
        single_excitation(0.3384430706501007, 0, 6),
        single_excitation(-0.01369705330580473, 11, 13),
        single_excitation(-0.0008308766409754753, 2, 5),
        single_excitation(0.05233951658010483, 9, 13),
        single_excitation(-0.060169387608766556, 1, 5),
        single_excitation(0.01605910062789917, 0, 5),
        double_excitation(0.011788561008870602, 4, 12, 7, 15),
        double_excitation(0.020096659660339355, 1, 9, 7, 15),
        double_excitation(-0.09507108479738235, 4, 12, 6, 14),
        double_excitation(-0.013540343381464481, 1, 9, 6, 14),
        double_excitation(0.05675666406750679, 0, 8, 6, 14),
        double_excitation(-0.004090831149369478, 4, 12, 5, 13),
        double_excitation(-0.03374265879392624, 3, 11, 5, 13),
        double_excitation(-0.07092584669589996, 2, 10, 5, 13),
        double_excitation(-0.020048394799232483, 1, 9, 5, 13),
        single_excitation(-0.025015711784362793, 11, 15),
        single_excitation(0.017067860811948776, 3, 7),
        single_excitation(0.03742631524801254, 9, 15),
        single_excitation(0.00033524437458254397, 1, 7),
        single_excitation(0.01046851184219122, 8, 15),
        single_excitation(-6.48947388981469e-05, 0, 7),
        single_excitation(-0.2677845358848572, 12, 14),
        single_excitation(0.5841130018234253, 4, 6),
        single_excitation(0.025380728766322136, 11, 14),
        single_excitation(0.04039718955755234, 3, 6),
        single_excitation(-0.007480979897081852, 10, 14),
        single_excitation(0.015186413191258907, 9, 14),
        single_excitation(0.1686946004629135, 8, 14),
        single_excitation(-0.1560288667678833, 0, 6),
        single_excitation(0.013483135029673576, 11, 13),
        single_excitation(0.012946118600666523, 3, 5),
        single_excitation(0.028197823092341423, 1, 5),
        double_excitation(0.028072049841284752, 3, 11, 7, 15),
        double_excitation(-0.01178472489118576, 2, 10, 7, 15),
        double_excitation(-0.002676451811566949, 1, 9, 7, 15),
        double_excitation(-0.034726642072200775, 2, 10, 6, 14),
        double_excitation(-0.03246036544442177, 1, 9, 6, 14),
        double_excitation(-0.0596524216234684, 0, 8, 6, 14),
        double_excitation(0.03394198790192604, 3, 11, 5, 13),
        double_excitation(-0.022588010877370834, 1, 9, 5, 13),
        single_excitation(0.026688629761338234, 4, 7),
        single_excitation(0.024984823539853096, 11, 15),
        single_excitation(-0.006861069239675999, 3, 7),
        single_excitation(0.24312496185302734, 12, 14),
        single_excitation(-0.026981592178344727, 2, 6),
        single_excitation(-0.015588995069265366, 9, 14),
        single_excitation(0.03613051027059555, 1, 6),
        single_excitation(-0.16282956302165985, 0, 6),
        single_excitation(-0.033322956413030624, 3, 5),
        single_excitation(0.0008328052936121821, 2, 5),
        single_excitation(-0.027516236528754234, 9, 13),
        double_excitation(0.02507351152598858, 4, 12, 7, 15),
        double_excitation(0.011557511053979397, 2, 10, 7, 15),
        double_excitation(-0.01780484803020954, 1, 9, 7, 15),
        double_excitation(-0.0047168065793812275, 0, 8, 7, 15),
        double_excitation(-0.033235207200050354, 3, 11, 6, 14),
        double_excitation(-0.021820662543177605, 2, 10, 6, 14),
        double_excitation(0.030478866770863533, 1, 9, 6, 14),
        double_excitation(-0.009895708411931992, 0, 8, 6, 14),
        double_excitation(-0.006865301169455051, 0, 8, 5, 13),
        single_excitation(-0.009236086159944534, 4, 7),
        single_excitation(0.004822351038455963, 3, 7),
        single_excitation(-0.010496580973267555, 8, 15),
        single_excitation(-0.0007604610291309655, 0, 7),
        single_excitation(-0.020210733637213707, 10, 14),
        single_excitation(-0.0009604869410395622, 2, 6),
        single_excitation(-0.04947235435247421, 1, 6),
        single_excitation(-0.17099782824516296, 8, 14),
        single_excitation(-1.4695104255224578e-05, 12, 13),
        single_excitation(-2.1170244508539326e-05, 4, 5),
        single_excitation(0.0201477762311697, 3, 5),
        single_excitation(-0.024071021005511284, 9, 13),
        single_excitation(0.03487590327858925, 1, 5),
        single_excitation(-0.015901213511824608, 0, 5),
        double_excitation(-0.03669343888759613, 4, 12, 7, 15),
        double_excitation(-0.028424132615327835, 3, 11, 7, 15),
        double_excitation(-0.05014651268720627, 3, 11, 6, 14),
        double_excitation(-0.0017477198271080852, 1, 9, 6, 14),
        double_excitation(-0.011541999876499176, 0, 8, 6, 14),
        double_excitation(-0.005993882194161415, 3, 11, 5, 13),
        double_excitation(-0.019160663709044456, 2, 10, 5, 13),
        double_excitation(0.005050677806138992, 1, 9, 5, 13),
    ]
    return Circuit(*gates, n_qubits=16)


circuit = build_beh2_npu_qas_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("BeH2_cir.png")
    plot(circuit, figure_path, title='BeH2 supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
