"""Auto-generated by demos/BeH2/BeH2.py.

supernet-searched ansatz that prepares the BeH2 active-space ground state.
Regenerate with: ``python -m demos.BeH2.BeH2``.
Plot with:       ``python -m demos.BeH2.BeH2_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, cx, hadamard, rx, ry, rz, rzz
from aicir.visual import plot


def build_beh2_npu_qas_circuit():
    """Return the supernet-searched BeH2 ground-state circuit."""
    gates = [
        rx(0.03628092259168625, 1),
        rx(0.02971269190311432, 2),
        ry(-0.037086207419633865, 3),
        ry(0.026685915887355804, 6),
        ry(0.03826207295060158, 7),
        rz(-0.0302717424929142, 9),
        hadamard(10),
        hadamard(11),
        ry(0.007364118006080389, 12),
        ry(0.013874996453523636, 13),
        ry(0.010933426208794117, 14),
        hadamard(15),
        cx(1, [0]),
        rzz(-0.04037543386220932, 1, 2),
        cx(3, [2]),
        cx(7, [6]),
        cx(8, [7]),
        rzz(0.01611914671957493, 8, 9),
        cx(11, [10]),
        cx(13, [12]),
        rzz(0.01319547276943922, 13, 14),
    ]
    return Circuit(*gates, n_qubits=16)


circuit = build_beh2_npu_qas_circuit()

circuit.plot()

if __name__ == "__main__":
    figure_path = Path(__file__).with_name("BeH2_cir.png")
    plot(circuit, figure_path, title='BeH2 supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
