"""Auto-generated by demos/CH4/CH4.py.

supernet-searched ansatz that prepares the CH4 active-space ground state.
Regenerate with: ``python -m demos.CH4.CH4``.
Plot with:       ``python -m demos.CH4.CH4_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, cx, hadamard, rx, ry, rz, rzz
from aicir.visual import plot


def build_ch4_npu_qas_circuit():
    """Return the supernet-searched CH4 ground-state circuit."""
    gates = [
        hadamard(0),
        hadamard(1),
        hadamard(4),
        rx(-1.5707883834838867, 6),
        ry(1.570796251296997, 7),
        hadamard(8),
        ry(-6.799978109484073e-07, 9),
        rx(-1.5705547332763672, 10),
        ry(-1.0698226690292358, 11),
        ry(-1.4832493206995423e-06, 12),
        hadamard(13),
        hadamard(15),
        hadamard(16),
        rzz(-3.9193100747070275e-06, 0, 1),
        cx(2, [1]),
        cx(4, [3]),
        rzz(-1.5707961320877075, 5, 6),
        rzz(-2.0824143575737253e-05, 6, 7),
        cx(8, [7]),
        rzz(-1.187973141670227, 8, 9),
        rzz(-1.5707916021347046, 9, 10),
        cx(13, [12]),
        rzz(1.6767747402191162, 16, 17),
        rx(-0.29450276494026184, 0),
        rz(0.816350519657135, 1),
        rz(0.7544463276863098, 2),
        rx(0.024956585839390755, 3),
        hadamard(4),
        ry(-3.3065516991115373e-10, 5),
        hadamard(6),
        hadamard(7),
        ry(-1.5708121061325073, 9),
        hadamard(10),
        ry(-1.0357481241226196, 11),
        hadamard(12),
        rx(-0.9906951189041138, 13),
        ry(1.5707902908325195, 14),
        ry(1.579834222793579, 15),
        hadamard(16),
        ry(1.4830222129821777, 17),
        rzz(-0.9740815162658691, 1, 2),
        cx(4, [3]),
        cx(5, [4]),
        rzz(1.1879700422286987, 7, 8),
        cx(9, [8]),
        rzz(-0.0018911807565018535, 9, 10),
        cx(11, [10]),
        cx(12, [11]),
        rzz(-1.6851467080414295e-05, 12, 13),
        rzz(-4.12307599617634e-06, 13, 14),
        cx(16, [15]),
        cx(17, [16]),
        rx(0.08392944186925888, 1),
        rx(-1.5707950592041016, 2),
        rz(-0.3618694543838501, 3),
        rz(-0.3282763659954071, 4),
        rx(0.014679805375635624, 7),
        ry(1.5707937479019165, 8),
        hadamard(9),
        ry(-1.0360214710235596, 11),
        rx(0.5857232809066772, 12),
        ry(1.5707967281341553, 13),
        ry(8.231469905695121e-08, 15),
        hadamard(16),
        rzz(-4.594661731971428e-06, 0, 1),
        cx(4, [3]),
        rzz(-0.8804475665092468, 4, 5),
        cx(6, [5]),
        cx(7, [6]),
        rzz(0.8938007354736328, 8, 9),
        cx(10, [9]),
        rzz(-0.030482446774840355, 10, 11),
        cx(12, [11]),
        rzz(-1.5707950592041016, 12, 13),
        rzz(1.117584702114982e-06, 14, 15),
        rzz(-1.4646397829055786, 15, 16),
        rzz(-0.08747094124555588, 16, 17),
        ry(1.5707967281341553, 0),
        hadamard(1),
        rz(-1.420097827911377, 4),
        rx(-1.4196091342455475e-06, 5),
        rx(-0.014679837971925735, 7),
        ry(3.3569067454664037e-06, 9),
        rz(0.18036091327667236, 10),
        rz(0.014138967730104923, 11),
        rx(-1.5707931518554688, 12),
        rz(-1.8048954010009766, 13),
        hadamard(14),
        rx(3.132411479949951, 15),
        hadamard(16),
        hadamard(17),
        cx(2, [1]),
        cx(3, [2]),
        cx(4, [3]),
        rzz(-1.2822293043136597, 5, 6),
        cx(7, [6]),
        cx(8, [7]),
        cx(9, [8]),
        rzz(0.2586451470851898, 9, 10),
        rzz(-0.023277252912521362, 10, 11),
        rzz(-0.7062859535217285, 11, 12),
        rzz(1.0487433671951294, 13, 14),
        rzz(-0.3130551278591156, 14, 15),
        rzz(0.8631369471549988, 15, 16),
    ]
    return Circuit(*gates, n_qubits=18)


circuit = build_ch4_npu_qas_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("CH4_cir.png")
    plot(circuit, figure_path, title='CH4 supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
