"""Auto-generated by demos/LiH.py.

supernet-searched ansatz that prepares the LiH active-space ground state.
Regenerate with: ``python -m demos.LiH``.
Plot with:       ``python -m demos.LiH_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, cx, hadamard, rx, ry, rzz
from aicir.visual import plot


def build_lih_qas_circuit():
    """Return the supernet-searched LiH ground-state circuit."""
    gates = [
        rx(1.5732789039611816, 0),
        hadamard(2),
        hadamard(3),
        cx(1, [0]),
        rzz(-0.0016766800545156002, 1, 2),
        rzz(-0.48043808341026306, 2, 3),
        rx(1.5718505382537842, 0),
        hadamard(1),
        rx(1.5658930540084839, 3),
        cx(1, [0]),
        rzz(3.148559808731079, 1, 2),
        cx(3, [2]),
        rx(-1.5748742818832397, 0),
        ry(1.596244215965271, 2),
        ry(1.0891057252883911, 3),
        cx(1, [0]),
        rzz(1.1253877878189087, 1, 2),
    ]
    return Circuit(*gates, n_qubits=4)


circuit = build_lih_qas_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("LiH_cir.png")
    plot(circuit, figure_path, title='LiH supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
