"""Quantum architecture search and state-synthesis utilities."""

from __future__ import annotations

from ._types import (
    ArchitectureScore,
    ArchitectureSpec,
    MetricDefinition,
    MetricGroupScore,
    SearchConfig,
    SearchResult,
)
from .architecture_candidates import build_common_architectures, common_architecture_names
from .architecture_search import ArchitectureSearch, NoiseAdaptiveQAS
from .evaluator import ArchitectureEvaluator, evaluate_architectures, metric_catalog
from .multi_objective_reward import (
    ExpressibilityScore,
    HardwareEfficiencyScore,
    MultiObjectiveReward,
    NoiseRobustnessScore,
    QASRewardWrapper,
    TrainabilityScore,
)
from .reward import RewardComposer, RewardWeights
from .search_env import NoisyQASEnv, QASState
from .task_evaluation import (
    OptimizerConfig,
    TaskEvaluationResult,
    bind_parameters,
    evaluate_task_objective,
    optimize_task_parameters,
)
from .vqe_hea_demo import (
    H2_HAMILTONIAN,
    H2_REFERENCE_ENERGY,
    HEAMask,
    HamiltonianProfile,
    ISING4_HAMILTONIAN,
    TFIMReferenceAlignmentReport,
    TFIMReferenceAlignmentRow,
    THETA_INIT_RANDOM_UNIFORM_PI,
    THETA_INIT_ZERO_DIAGNOSTIC,
    V3_COBYLA_RHOBEG,
    V3_COBYLA_TOL,
    VQEB2ReliabilityReport,
    VQEEnumerationReport,
    VQEFairStabilityReport,
    VQEHEADemoReport,
    VQEDemoProblem,
    VQETrainabilityPriorReport,
    analyze_hamiltonian,
    architecture_from_hea_mask,
    adaptive_fair_n_starts,
    b1_bottom_filter,
    derive_priority_seed_masks,
    diagnose_theta_randomness,
    enumerate_hea_masks,
    evaluate_h2_energy,
    evaluate_vqe_energy,
    exact_ground_energy,
    get_structure_family,
    h2_demo_problem,
    hamiltonian_matrix,
    hamiltonian_aware_mask_preferences,
    is_hamiltonian_favored_family,
    is_b1_improvement_valid,
    ising4_demo_problem,
    mutate_hea_mask,
    mutate_hea_mask_hamiltonian_aware,
    optimize_h2_energy,
    optimize_vqe_energy,
    resolve_qas_backend,
    rotation_only_ansatz,
    run_ising4_b2_reliability_experiment,
    run_ising4_fair_vqe_stability_experiment,
    run_ising4_final_multiseed_validation,
    run_ising4_full_enumeration_baseline,
    run_ising4_trainability_prior_demo,
    run_tfim_full_enumeration_baseline,
    run_tfim_priority_seed_validation,
    run_tfim_stage1_stage2_search,
    run_sa_search,
    stratified_stage1_pool,
    tfim_chain_demo_problem,
    tfim_chain_hamiltonian,
    tfim_open_chain_free_fermion_ground_energy,
    update_beam,
    validate_tfim_reference_alignment,
    v3_final_maxfev,
    v3_screening_maxfev,
    v3_top_k,
    run_vqe_hea_demo,
    run_vqe_ising4_demo,
    zero_cost_guardrail,
)
from .experiments import (
    MultiSeedValidationReport,
    ValidationReport,
    run_hybrid_qas_validation_experiment,
    run_multi_seed_validation_experiment,
    run_task_feedback_validation_experiment,
    run_validation_experiment,
)
from .problems import (
    MaxCutInstance,
    ProblemInstance,
    ResourceAllocationInstance,
    maxcut_line,
    maxcut_ring,
    small_resource_allocation,
)
from ..metrics.expressibility import KL_Haar_divergence, KL_Haar_relative, MMD_relative
from ..metrics.hardware import HardwareProfile
from ..metrics.noisy_expressibility import (
    KL_Haar_noisy,
    MMD_noisy,
    comparative_expressibility,
    expressibility_score,
)
from ..channel.noise import (
    IonTrapNoiseConfig,
    NoiseSensitivityResult,
    load_default_ion_trap_noise_config,
    load_ion_trap_noise_config,
    noise_sensitivity,
)
from ..channel.noise.metrics import ion_trap_error_budget_proxy

_OPTIONAL_RL_EXPORTS: list[str] = []
try:
    from . import config
    from .CRLQAS import AdamSPSAConfig, CRLQASConfig, CRLQASResult, crlqas, train_crlqas
    from .PPR_DQL import PPRDQLConfig, PPRDQLPolicy, PPRDQLResult, ppr_dql_state_to_circuit, train_ppr_dql
    from .PPO_RB import PPORollbackConfig, ppo_rb_qas
    from .runner import QASRunConfig, available_qas_methods, default_qas_config, run
    from .VQA_QAS import (
        Architecture,
        LayerArchitecture,
        VQAQAS,
        VQAQASConfig,
        VQAQASResult,
        classification_vqa_qas,
        h2_vqe_qas,
        train_vqa_qas,
        vqa_qas,
    )
except ModuleNotFoundError as exc:
    if exc.name != "torch":
        raise
else:
    _OPTIONAL_RL_EXPORTS.extend(
        [
            "AdamSPSAConfig",
            "Architecture",
            "CRLQASConfig",
            "CRLQASResult",
            "LayerArchitecture",
            "PPRDQLConfig",
            "PPRDQLPolicy",
            "PPRDQLResult",
            "PPORollbackConfig",
            "QASRunConfig",
            "VQAQAS",
            "VQAQASConfig",
            "VQAQASResult",
            "available_qas_methods",
            "classification_vqa_qas",
            "config",
            "crlqas",
            "default_qas_config",
            "h2_vqe_qas",
            "ppr_dql_state_to_circuit",
            "ppo_rb_qas",
            "run",
            "train_crlqas",
            "train_ppr_dql",
            "train_vqa_qas",
            "vqa_qas",
        ]
    )

__all__ = [
    "ArchitectureEvaluator",
    "ArchitectureScore",
    "ArchitectureSearch",
    "ArchitectureSpec",
    "ExpressibilityScore",
    "H2_HAMILTONIAN",
    "H2_REFERENCE_ENERGY",
    "HEAMask",
    "HamiltonianProfile",
    "ISING4_HAMILTONIAN",
    "HardwareEfficiencyScore",
    "HardwareProfile",
    "IonTrapNoiseConfig",
    "KL_Haar_divergence",
    "KL_Haar_noisy",
    "KL_Haar_relative",
    "MMD_noisy",
    "MMD_relative",
    "MetricDefinition",
    "MetricGroupScore",
    "MultiSeedValidationReport",
    "MultiObjectiveReward",
    "NoiseAdaptiveQAS",
    "NoiseRobustnessScore",
    "NoiseSensitivityResult",
    "NoisyQASEnv",
    "OptimizerConfig",
    "ProblemInstance",
    "QASRewardWrapper",
    "QASState",
    "ResourceAllocationInstance",
    "RewardComposer",
    "RewardWeights",
    "SearchConfig",
    "SearchResult",
    "TaskEvaluationResult",
    "TFIMReferenceAlignmentReport",
    "TFIMReferenceAlignmentRow",
    "THETA_INIT_RANDOM_UNIFORM_PI",
    "THETA_INIT_ZERO_DIAGNOSTIC",
    "TrainabilityScore",
    "V3_COBYLA_RHOBEG",
    "V3_COBYLA_TOL",
    "ValidationReport",
    "VQEB2ReliabilityReport",
    "VQEEnumerationReport",
    "VQEFairStabilityReport",
    "VQEHEADemoReport",
    "VQEDemoProblem",
    "VQETrainabilityPriorReport",
    "MaxCutInstance",
    "analyze_hamiltonian",
    "architecture_from_hea_mask",
    "adaptive_fair_n_starts",
    "b1_bottom_filter",
    "derive_priority_seed_masks",
    "diagnose_theta_randomness",
    "bind_parameters",
    "build_common_architectures",
    "common_architecture_names",
    "comparative_expressibility",
    "evaluate_task_objective",
    "evaluate_architectures",
    "evaluate_h2_energy",
    "evaluate_vqe_energy",
    "enumerate_hea_masks",
    "exact_ground_energy",
    "expressibility_score",
    "get_structure_family",
    "h2_demo_problem",
    "hamiltonian_matrix",
    "hamiltonian_aware_mask_preferences",
    "is_hamiltonian_favored_family",
    "is_b1_improvement_valid",
    "ion_trap_error_budget_proxy",
    "ising4_demo_problem",
    "load_default_ion_trap_noise_config",
    "load_ion_trap_noise_config",
    "maxcut_line",
    "maxcut_ring",
    "metric_catalog",
    "mutate_hea_mask",
    "mutate_hea_mask_hamiltonian_aware",
    "noise_sensitivity",
    "optimize_task_parameters",
    "optimize_h2_energy",
    "optimize_vqe_energy",
    "resolve_qas_backend",
    "rotation_only_ansatz",
    "run_ising4_b2_reliability_experiment",
    "run_ising4_fair_vqe_stability_experiment",
    "run_ising4_final_multiseed_validation",
    "run_ising4_full_enumeration_baseline",
    "run_ising4_trainability_prior_demo",
    "run_tfim_full_enumeration_baseline",
    "run_tfim_priority_seed_validation",
    "run_tfim_stage1_stage2_search",
    "run_sa_search",
    "stratified_stage1_pool",
    "tfim_chain_demo_problem",
    "tfim_chain_hamiltonian",
    "tfim_open_chain_free_fermion_ground_energy",
    "update_beam",
    "validate_tfim_reference_alignment",
    "v3_final_maxfev",
    "v3_screening_maxfev",
    "v3_top_k",
    "run_validation_experiment",
    "run_hybrid_qas_validation_experiment",
    "run_multi_seed_validation_experiment",
    "run_task_feedback_validation_experiment",
    "run_vqe_hea_demo",
    "run_vqe_ising4_demo",
    "small_resource_allocation",
    "zero_cost_guardrail",
] + _OPTIONAL_RL_EXPORTS
