"""Auto-generated by demos/H2O/H2O_dqas.py.

NPU DQAS searched excitation ansatz preparing the H2O active-space ground state.
Regenerate with: ``python -m demos.H2O.H2O_dqas``.
Plot with:       ``python -m demos.H2O.H2O_dqas_npu_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, double_excitation, pauli_x, single_excitation
from aicir.visual import plot
from aicir.transpile import optimize


def build_h2o_dqas_npu_circuit():
    """Return the NPU DQAS-searched H2O ground-state circuit."""
    gates = [
        pauli_x(1),
        pauli_x(2),
        pauli_x(4),
        pauli_x(5),
        double_excitation(-0.06401093304157257, 0, 3, 1, 4),
        single_excitation(0.0051124910824000835, 3, 5),
    ]
    return Circuit(*gates, n_qubits=6)


circuit = build_h2o_dqas_npu_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("H2O_dqas_npu_cir.png")
    optimized = optimize(circuit)
    print(f"Optimized circuit: {len(circuit.gates)} -> {len(optimized.gates)} gates")
    plot(optimized, figure_path, title='H2O DQAS ground-state ansatz (NPU)')
    print(f"Saved circuit figure to {figure_path}")
