"""Auto-generated by demos/H2O/H2O_qdrats.py.

QDRATS (QuantumDARTS) searched ansatz preparing the H2O active-space ground state.
Regenerate with: ``python -m demos.H2O.H2O_qdrats``.
Plot with:       ``python -m demos.H2O.H2O_qdrats_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, double_excitation, pauli_x, single_excitation
from aicir.visual import plot
from aicir.transpile import optimize


def build_h2o_qdrats_circuit():
    """Return the supernet-searched H2O ground-state circuit."""
    gates = [
        pauli_x(1),
        pauli_x(2),
        pauli_x(4),
        pauli_x(5),
        single_excitation(0.008771187625825405, 0, 1),
        single_excitation(-0.0087812514975667, 0, 1),
        double_excitation(-0.09347401559352875, 0, 3, 2, 5),
        double_excitation(-0.06012396141886711, 0, 3, 1, 4),
    ]
    return Circuit(*gates, n_qubits=6)


circuit = build_h2o_qdrats_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("H2O_qdrats_cir.png")
    optimized = optimize(circuit)
    print(f"Optimized circuit: {len(circuit.gates)} -> {len(optimized.gates)} gates")
    plot(optimized, figure_path, title='H2O QDRATS ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
