"""Auto-generated by demos/H2O/H2O.py.

supernet-searched ansatz that prepares the H2O active-space ground state.
Regenerate with: ``python -m demos.H2O.H2O``.
Plot with:       ``python -m demos.H2O.H2O_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, double_excitation, pauli_x, single_excitation
from aicir.visual import plot


def build_h2o_qas_circuit():
    """Return the supernet-searched H2O ground-state circuit."""
    gates = [
        pauli_x(1),
        pauli_x(2),
        pauli_x(4),
        pauli_x(5),
        single_excitation(-0.08856074512004852, 0, 1),
        single_excitation(0.05636700242757797, 3, 5),
        single_excitation(0.10316292196512222, 0, 2),
        double_excitation(-0.0025043997447937727, 0, 3, 2, 5),
        double_excitation(0.06324798613786697, 0, 3, 1, 4),
        single_excitation(-0.05291515216231346, 0, 2),
        single_excitation(0.10108549147844315, 0, 1),
        single_excitation(-0.07965152710676193, 3, 5),
        single_excitation(-0.08546676486730576, 0, 1),
        double_excitation(0.23781652748584747, 0, 3, 1, 4),
        single_excitation(-0.03794153034687042, 3, 5),
        single_excitation(0.010671698488295078, 0, 2),
        single_excitation(-0.04534510150551796, 3, 4),
        double_excitation(-0.26783254742622375, 0, 3, 2, 5),
        double_excitation(-0.37631604075431824, 0, 3, 1, 4),
        single_excitation(0.08034158498048782, 3, 5),
        single_excitation(-0.06099451705813408, 0, 2),
        single_excitation(0.0434163399040699, 3, 4),
        single_excitation(0.06510613858699799, 0, 1),
        double_excitation(0.1725027710199356, 0, 3, 2, 5),
        double_excitation(0.011300916783511639, 0, 3, 1, 4),
    ]
    return Circuit(*gates, n_qubits=6)


circuit = build_h2o_qas_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("H2O_cir.png")
    plot(circuit, figure_path, title='H2O supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
