"""Flat, orthogonal evaluator for architecture-level QAS."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence

import numpy as np

from ...backends.base import Backend
from ...noise.analysis import noise_sensitivity
from ...noise.metrics import ion_trap_error_budget_proxy
from ...noise.model import NoiseModel
from ._types import ArchitectureScore, ArchitectureSpec, MetricDefinition, MetricGroupScore
from ._utils import assign_ranks, clipped_score, ensure_backend
from ...metrics.expressibility import KL_Haar_divergence, MMD_relative
from ...metrics.hardware import (
    HardwareProfile,
    native_depth_twoq_efficiency,
    native_depth_twoq_efficiency_details,
    topology_mapping_efficiency,
    topology_mapping_efficiency_details,
)
from ...metrics.trainability import (
    local_probe_gradient_statistics,
    structure_proxy,
    structure_proxy_details,
)
from .reward import RewardComposer, RewardWeights


def metric_catalog(active_metrics: Optional[Dict[str, str]] = None) -> Dict[str, List[MetricDefinition]]:
    active_metrics = active_metrics or {}
    catalog = {
        "expressibility": [
            MetricDefinition("kl_haar", "KL divergence from the Haar fidelity distribution", "implemented"),
            MetricDefinition("mmd_relative", "MMD distance to Haar-like samples", "implemented"),
            MetricDefinition("frame_potential", "Distance from unitary/state design behavior", "todo"),
            MetricDefinition("entangling_capability", "Average entanglement generated by sampled parameters", "todo"),
            MetricDefinition("transformer_predictor", "Learned surrogate for expressibility", "todo"),
        ],
        "trainability": [
            MetricDefinition("structure_proxy", "Depth, two-qubit density, and parameter-count heuristic", "implemented"),
            MetricDefinition("gradient_variance", "Task-agnostic local-probe parameter-gradient variance", "implemented"),
            MetricDefinition("gradient_norm", "Task-agnostic local-probe gradient norm statistics", "implemented"),
            MetricDefinition("barren_plateau_risk", "Risk estimate from expressibility, depth, and noise", "todo"),
        ],
        "noise_robustness": [
            MetricDefinition("ion_trap_error_budget_proxy", "Ion-trap error budget from the default noise configuration", "implemented"),
            MetricDefinition("ideal_noisy_score_gap", "Direct ideal-vs-noisy score gap", "todo"),
            MetricDefinition("noise_sensitivity", "Ideal-vs-noisy fidelity under a provided NoiseModel", "implemented"),
            MetricDefinition("per_source_ablation", "Noise-source ablation such as idle/crosstalk/twoq", "todo"),
        ],
        "hardware_efficiency": [
            MetricDefinition("native_depth_twoq_efficiency", "Native-gate, depth, and two-qubit-count heuristic", "implemented"),
            MetricDefinition("topology_mapping_efficiency", "Native-gate, topology, routing, and depth mapping efficiency", "implemented"),
            MetricDefinition("connectivity_penalty", "Penalty from non-native connectivity or routing cost", "todo"),
            MetricDefinition("calibrated_error_cost", "Hardware-calibrated error/resource cost", "todo"),
            MetricDefinition("latency_cost", "Gate-time or schedule-length cost", "todo"),
        ],
    }
    defaults = {
        "expressibility": "kl_haar",
        "trainability": "structure_proxy",
        "noise_robustness": "ion_trap_error_budget_proxy",
        "hardware_efficiency": "native_depth_twoq_efficiency",
    }
    for group_name, metrics in catalog.items():
        active_name = active_metrics.get(group_name, defaults[group_name])
        for metric in metrics:
            metric.active = metric.name == active_name
    return catalog


class ArchitectureEvaluator:
    """Evaluate candidates with one active metric per orthogonal objective group."""

    def __init__(
        self,
        backend: Optional[Backend] = None,
        noise_model: Optional[NoiseModel] = None,
        hardware_profile: Optional[HardwareProfile] = None,
        weights: Optional[RewardWeights] = None,
        n_samples: int = 200,
        active_metrics: Optional[Dict[str, str]] = None,
    ):
        self.backend = backend
        self.noise_model = noise_model
        self.hardware_profile = hardware_profile
        self.weights = weights or RewardWeights()
        self.reward_composer = RewardComposer(self.weights)
        self.n_samples = int(n_samples)
        self.active_metrics = active_metrics or {}

    def _active_metric_definition(self, group_name: str) -> MetricDefinition:
        catalog = metric_catalog(self.active_metrics)
        active = [metric for metric in catalog[group_name] if metric.active]
        if not active:
            requested = self.active_metrics.get(group_name)
            available = ", ".join(metric.name for metric in catalog[group_name])
            raise ValueError(f"Unknown {group_name} metric {requested!r}. Available metrics: {available}")
        metric = active[0]
        if metric.status != "implemented":
            raise NotImplementedError(f"{group_name} metric {metric.name!r} is marked as {metric.status!r}")
        return metric

    def _active_metric_name(self, group_name: str) -> str:
        return self._active_metric_definition(group_name).name

    def _group_score(
        self,
        group_name: str,
        score: float,
        raw_values: Optional[Dict[str, Any]] = None,
        notes: Optional[List[str]] = None,
    ) -> MetricGroupScore:
        catalog = metric_catalog(self.active_metrics)
        active = self._active_metric_definition(group_name).name
        return MetricGroupScore(
            name=group_name,
            active_metric=active,
            metrics=catalog[group_name],
            score=clipped_score(score),
            raw_values=raw_values or {},
            notes=notes or [],
        )

    def _evaluate_expressibility(self, architecture: ArchitectureSpec, backend: Backend) -> MetricGroupScore:
        metric_name = self._active_metric_name("expressibility")
        if metric_name == "kl_haar":
            try:
                distance = KL_Haar_divergence(architecture.circuit, samples=self.n_samples, backend=backend)
                score = float(np.exp(-distance))
            except Exception:
                score = structure_proxy(architecture.circuit)
                return self._group_score("expressibility", score, {"fallback_score": score}, ["Fell back to structural proxy."])
            return self._group_score("expressibility", score, {"kl_haar_score": score})
        if metric_name == "mmd_relative":
            score = MMD_relative(architecture.circuit, samples=self.n_samples, backend=backend)
            return self._group_score("expressibility", score, {"mmd_relative_score": score})
        raise NotImplementedError(f"Unsupported expressibility metric: {metric_name}")

    def _evaluate_trainability(self, architecture: ArchitectureSpec) -> MetricGroupScore:
        metric_name = self._active_metric_name("trainability")
        if metric_name == "structure_proxy":
            score = structure_proxy(architecture.circuit)
            return self._group_score("trainability", score, structure_proxy_details(architecture.circuit))
        if metric_name == "gradient_norm":
            samples = max(1, min(self.n_samples, 16))
            raw_values = local_probe_gradient_statistics(architecture.circuit, samples=samples, backend=None)
            scale = 1.0 / max(1, int(architecture.circuit.n_qubits))
            score = float(np.clip(1.0 - np.exp(-raw_values["mean_gradient_norm"] / max(scale, 1e-12)), 0.0, 1.0))
            return self._group_score("trainability", score, {"gradient_norm_score": score, **raw_values})
        if metric_name == "gradient_variance":
            samples = max(2, min(self.n_samples, 16))
            raw_values = local_probe_gradient_statistics(architecture.circuit, samples=samples, backend=None)
            scale = 1.0 / max(1, int(architecture.circuit.n_qubits)) ** 2
            variance_score = 1.0 - np.exp(-raw_values["gradient_variance"] / max(scale, 1e-12))
            norm_score = 1.0 - np.exp(-raw_values["mean_gradient_norm"] / max(np.sqrt(scale), 1e-12))
            score = float(np.clip(0.65 * variance_score + 0.35 * norm_score, 0.0, 1.0))
            return self._group_score("trainability", score, {"gradient_variance_score": score, **raw_values})
        raise NotImplementedError(f"Unsupported trainability metric: {metric_name}")

    def _evaluate_noise_robustness(self, architecture: ArchitectureSpec, backend: Backend) -> MetricGroupScore:
        metric_name = self._active_metric_name("noise_robustness")
        circuit = architecture.circuit
        if metric_name == "ion_trap_error_budget_proxy":
            score, raw_values = ion_trap_error_budget_proxy(circuit)
            notes = []
            if self.noise_model is not None:
                notes.append("Provided noise_model ignored by ion_trap_error_budget_proxy; select noise_sensitivity to use it.")
            return self._group_score(
                "noise_robustness",
                score,
                {"ion_trap_error_budget_proxy_score": score, **raw_values},
                notes,
            )
        if metric_name == "noise_sensitivity":
            if self.noise_model is None:
                raise ValueError("noise_sensitivity requires ArchitectureEvaluator(noise_model=...).")
            result = noise_sensitivity(circuit, backend=backend, noise_model=self.noise_model, n_samples=self.n_samples)
            score = 1.0 - result.avg_fidelity_loss
            return self._group_score(
                "noise_robustness",
                score,
                {
                    "noise_sensitivity_score": score,
                    "ideal_avg_fidelity": result.ideal_avg_fidelity,
                    "noisy_avg_fidelity": result.noisy_avg_fidelity,
                    "avg_fidelity_loss": result.avg_fidelity_loss,
                    "gate_type_sensitivity": dict(result.gate_type_sensitivity),
                    "n_gates_total": result.n_gates_total,
                    "n_gates_by_type": dict(result.n_gates_by_type),
                    "noise_strength": result.noise_strength,
                },
            )
        raise NotImplementedError(f"Unsupported noise robustness metric: {metric_name}")

    def _evaluate_hardware_efficiency(self, architecture: ArchitectureSpec) -> MetricGroupScore:
        metric_name = self._active_metric_name("hardware_efficiency")
        if metric_name == "native_depth_twoq_efficiency":
            score = native_depth_twoq_efficiency(architecture.circuit)
            return self._group_score(
                "hardware_efficiency",
                score,
                native_depth_twoq_efficiency_details(architecture.circuit),
            )
        if metric_name == "topology_mapping_efficiency":
            score = topology_mapping_efficiency(architecture.circuit, profile=self.hardware_profile)
            return self._group_score(
                "hardware_efficiency",
                score,
                topology_mapping_efficiency_details(architecture.circuit, profile=self.hardware_profile),
            )
        raise NotImplementedError(f"Unsupported hardware efficiency metric: {metric_name}")

    def evaluate(self, architecture: ArchitectureSpec) -> ArchitectureScore:
        backend = ensure_backend(self.backend)
        self.backend = backend

        expressibility = self._evaluate_expressibility(architecture, backend)
        trainability = self._evaluate_trainability(architecture)
        noise_robustness = self._evaluate_noise_robustness(architecture, backend)
        hardware_efficiency = self._evaluate_hardware_efficiency(architecture)

        score = ArchitectureScore(
            architecture=architecture,
            expressibility=expressibility,
            trainability=trainability,
            noise_robustness=noise_robustness,
            hardware_efficiency=hardware_efficiency,
            weights=self.weights.to_dict(),
            weighted_score=0.0,
        )
        score.weighted_score = self.reward_composer.compose_architecture_score(score)
        return score

    def evaluate_many(self, architectures: Sequence[ArchitectureSpec]) -> List[ArchitectureScore]:
        return assign_ranks([self.evaluate(architecture) for architecture in architectures])


def evaluate_architectures(
    architectures: Sequence[ArchitectureSpec],
    backend: Optional[Backend] = None,
    noise_model: Optional[NoiseModel] = None,
    hardware_profile: Optional[HardwareProfile] = None,
    weights: Optional[RewardWeights] = None,
    n_samples: int = 200,
    active_metrics: Optional[Dict[str, str]] = None,
) -> List[ArchitectureScore]:
    evaluator = ArchitectureEvaluator(
        backend=backend,
        noise_model=noise_model,
        hardware_profile=hardware_profile,
        weights=weights,
        n_samples=n_samples,
        active_metrics=active_metrics,
    )
    return evaluator.evaluate_many(architectures)



__all__ = [
    "ArchitectureEvaluator",
    "evaluate_architectures",
    "metric_catalog",
]




