"""Auto-generated by demos/LiH.py.

VQA_QAS-searched ansatz that prepares the LiH active-space ground state.
Regenerate with: ``python -m demos.LiH``.
Plot with:       ``python -m demos.LiH_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, cx, hadamard, rx, ry, rz, rzz
from aicir.visual import plot


def build_lih_qas_circuit():
    """Return the VQA_QAS-searched LiH ground-state circuit."""
    gates = [
        hadamard(0),
        rx(0.009173969738185406, 1),
        rx(0.06688184291124344, 2),
        rzz(0.3608277440071106, 0, 1),
        cx(2, [1]),
        rzz(-1.0542840957641602, 2, 3),
        rz(-0.7721207737922668, 0),
        ry(0.00041822140337899327, 1),
        ry(0.054266925901174545, 2),
        rz(0.5727043151855469, 3),
        rzz(0.41053852438926697, 0, 1),
        cx(2, [1]),
        cx(3, [2]),
        ry(1.5671398639678955, 0),
        ry(0.003961021080613136, 1),
        rx(0.033638905733823776, 2),
        hadamard(3),
        cx(1, [0]),
        rzz(1.4712622165679932, 1, 2),
        rzz(0.27347472310066223, 2, 3),
    ]
    return Circuit(*gates, n_qubits=4)


circuit = build_lih_qas_circuit()

circuit.plot()