"""Auto-generated by demos/LiH.py.

supernet-searched ansatz that prepares the LiH active-space ground state.
Regenerate with: ``python -m demos.LiH``.
Plot with:       ``python -m demos.LiH_cir``.
"""

from __future__ import annotations

from pathlib import Path

from aicir.core.circuit import Circuit, cx, hadamard, rx, ry, rzz
from aicir.visual import plot


def build_lih_qas_circuit():
    """Return the supernet-searched LiH ground-state circuit."""
    gates = [
        rx(1.5732791423797607, 0),
        hadamard(2),
        hadamard(3),
        cx(1, [0]),
        rzz(-0.001676645944826305, 1, 2),
        rzz(-0.48043856024742126, 2, 3),
        rx(1.571850299835205, 0),
        hadamard(1),
        rx(1.5658926963806152, 3),
        cx(1, [0]),
        rzz(3.1485607624053955, 1, 2),
        cx(3, [2]),
        rx(-1.574873924255371, 0),
        ry(1.5962427854537964, 2),
        ry(1.089105248451233, 3),
        cx(1, [0]),
        rzz(1.1253852844238281, 1, 2),
    ]
    return Circuit(*gates, n_qubits=4)


circuit = build_lih_qas_circuit()


if __name__ == "__main__":
    figure_path = Path(__file__).with_name("lih_vqa_qas_circuit.png")
    plot(circuit, figure_path, title='LiH supernet ground-state ansatz')
    print(f"Saved circuit figure to {figure_path}")
