"""MaxCut Ising 哈密顿量与对应的 VQE 基态线路（自动生成）。

本文件由 ``demos/MaxCut/maxcut.py`` 生成，请勿手工编辑。

包含：
- 随机图的节点数与边集；
- MaxCut Ising 哈密顿量项 ``MAXCUT_HAMILTONIAN_TERMS``；
- ``aicir.qas.supernet`` 搜索 + 微调得到的 VQE 线路 ``VQE_CIRCUIT_JSON``；
- 重建辅助函数 ``build_hamiltonian()`` / ``build_vqe_circuit()``。
"""

from __future__ import annotations

from aicir import Circuit
from aicir.channel.operators import Hamiltonian
from aicir.core.io.json_io import circuit_from_json

# ── 随机图 ────────────────────────────────────────────────────────────────
N_NODES = 7
# (节点 i, 节点 j, 边权 w)
EDGES = [(0, 3, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (1, 2, 1.0),
 (1, 3, 1.0),
 (1, 6, 1.0),
 (2, 4, 1.0),
 (3, 6, 1.0),
 (4, 6, 1.0)]

# ── MaxCut Ising 哈密顿量 ───────────────────────────────────────────────────
# 项格式：("ZZ", [i, j], coeff) 或 ("I"*N_NODES, const)。
MAXCUT_HAMILTONIAN_TERMS = [('ZZ', [0, 3], 0.5),
 ('ZZ', [0, 4], 0.5),
 ('ZZ', [0, 5], 0.5),
 ('ZZ', [1, 2], 0.5),
 ('ZZ', [1, 3], 0.5),
 ('ZZ', [1, 6], 0.5),
 ('ZZ', [2, 4], 0.5),
 ('ZZ', [3, 6], 0.5),
 ('ZZ', [4, 6], 0.5),
 ('IIIIIII', -4.5)]


def build_hamiltonian() -> Hamiltonian:
    """重建 MaxCut Ising 哈密顿量。"""
    return Hamiltonian(n_qubits=N_NODES, terms=MAXCUT_HAMILTONIAN_TERMS)


# ── VQE 基态线路（QAS supernet 搜索并微调）────────────────────────────────────
# 指标（基于归一化态重新计算）：vqe_energy 为线路能量，expected_cut 为能量
# 期望对应的割值，achieved_cut 为概率显著比特串中的最佳读出割值。
VQE_METRICS = {'vqe_energy': -6.999990463256836,
 'exact_ground_energy': -8.0,
 'max_cut': 8.0,
 'expected_cut': 6.999990463256836,
 'achieved_cut': 7.0,
 'approx_ratio': 0.875,
 'expected_approx_ratio': 0.8749988079071045,
 'n_gates': 81}

# 线路以 circuit-JSON 形式记录，可用 circuit_from_json 无损重建。
VQE_CIRCUIT_JSON = ('{\n'
 '  "format": "aicir.circuit",\n'
 '  "version": "1.0",\n'
 '  "n_qubits": 7,\n'
 '  "gates": [\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": -0.05282989516854286\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": -0.7830110192298889\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 3\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 4\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 5\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 1,\n'
 '      "parameter": -0.007814858108758926\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": -0.034527163952589035\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.0003518603043630719\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 3,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": -0.017638880759477615\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 3,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": 0.0010337184648960829\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 4,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": 0.7175514101982117\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": -5.083885116619058e-05\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": 0.03470027074217796\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 0.0018162019550800323\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": 0.3000406324863434\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 1,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.4133986234664917\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 3,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": 0.018806669861078262\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 4,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": 0.8754278421401978\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 0\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 0.2467985302209854\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": -0.7888134121894836\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 3,\n'
 '      "parameter": -0.4076882004737854\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 0.0006002276786603034\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": -0.19688037037849426\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 6\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 1,\n'
 '      "parameter": 5.695696745533496e-05\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.36362504959106445\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": 6.83859980199486e-06\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": 2.935524025815539e-05\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        5\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 0\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 0.00014291360275819898\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": 2.3551774575025775e-07\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 3,\n'
 '      "parameter": -0.3846818506717682\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": -0.7791584730148315\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 6,\n'
 '      "parameter": 1.5741136074066162\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        5\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 2\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 3\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 0.3509121239185333\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": -0.7691136598587036\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 6,\n'
 '      "parameter": 0.3495274782180786\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 1,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": 0.9318757057189941\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": -0.6399701237678528\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 3,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": -0.8027370572090149\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        5\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 7.254033698700368e-05\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 2\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 3,\n'
 '      "parameter": -5.851581954630092e-05\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 0.14308542013168335\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 5\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 6,\n'
 '      "parameter": 0.7633461952209473\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 1,\n'
 '      "parameter": -0.6439037919044495\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": 0.267911434173584\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.006014642305672169\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": 0.3004915416240692\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 3,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": 0.2069288045167923\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 6,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    }\n'
 '  ]\n'
 '}')


def build_vqe_circuit() -> Circuit:
    """重建 QAS 搜索得到的 VQE 基态线路。"""
    return circuit_from_json(VQE_CIRCUIT_JSON)
