"""MaxCut Ising 哈密顿量与对应的 VQE 基态线路（自动生成）。

本文件由 ``demos/MaxCut/maxcut.py`` 生成，请勿手工编辑。

包含：
- 随机图的节点数与边集；
- MaxCut Ising 哈密顿量项 ``MAXCUT_HAMILTONIAN_TERMS``；
- ``aicir.qas.algorithms.supernet`` 搜索 + 微调得到的 VQE 线路 ``VQE_CIRCUIT_JSON``；
- 重建辅助函数 ``build_hamiltonian()`` / ``build_vqe_circuit()``。
"""

from __future__ import annotations

from aicir import Circuit
from aicir.core.operators import Hamiltonian
from aicir.core.io.json_io import circuit_from_json

# ── 随机图 ────────────────────────────────────────────────────────────────
N_NODES = 6
# (节点 i, 节点 j, 边权 w)
EDGES = [(0, 1, 1.0),
 (0, 3, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (1, 3, 1.0),
 (1, 4, 1.0),
 (2, 3, 1.0),
 (2, 4, 1.0),
 (3, 4, 1.0)]

# ── MaxCut Ising 哈密顿量 ───────────────────────────────────────────────────
# 项格式：("ZZ", [i, j], coeff) 或 ("I"*N_NODES, const)。
MAXCUT_HAMILTONIAN_TERMS = [('ZZ', [0, 1], 0.5),
 ('ZZ', [0, 3], 0.5),
 ('ZZ', [0, 4], 0.5),
 ('ZZ', [0, 5], 0.5),
 ('ZZ', [1, 3], 0.5),
 ('ZZ', [1, 4], 0.5),
 ('ZZ', [2, 3], 0.5),
 ('ZZ', [2, 4], 0.5),
 ('ZZ', [3, 4], 0.5),
 ('IIIIII', -4.5)]


def build_hamiltonian() -> Hamiltonian:
    """重建 MaxCut Ising 哈密顿量。"""
    return Hamiltonian(n_qubits=N_NODES, terms=MAXCUT_HAMILTONIAN_TERMS)


# ── VQE 基态线路（QAS supernet 搜索并微调）────────────────────────────────────
# 指标（基于归一化态重新计算）：vqe_energy 为线路能量，expected_cut 为能量
# 期望对应的割值，achieved_cut 为概率显著比特串中的最佳读出割值。
VQE_METRICS = {'vqe_energy': -6.4999494552612305,
 'exact_ground_energy': -7.0,
 'max_cut': 7.0,
 'expected_cut': 6.4999494552612305,
 'achieved_cut': 7.0,
 'approx_ratio': 1.0,
 'expected_approx_ratio': 0.9285642078944615,
 'n_gates': 70}

# 线路以 circuit-JSON 形式记录，可用 circuit_from_json 无损重建。
VQE_CIRCUIT_JSON = ('{\n'
 '  "format": "aicir.circuit",\n'
 '  "version": "1.0",\n'
 '  "n_qubits": 6,\n'
 '  "gates": [\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 0\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": -0.004578222520649433\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 3\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 1.569815993309021\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": -0.02054651640355587\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 4,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": 0.7321543097496033\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 0,\n'
 '      "parameter": 0.004575303755700588\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": 0.5179712176322937\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 3,\n'
 '      "parameter": 0.0021235153544694185\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 4\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": 0.7862485647201538\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        0\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": -0.6391825675964355\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.7342314124107361\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": 0.00019213458290323615\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 0.4830304980278015\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": -0.6435890793800354\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 3,\n'
 '      "parameter": -1.5752243995666504\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": 0.7833465337753296\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 1,\n'
 '      "parameter": 0.5459701418876648\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": 0.5048015117645264\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": -0.7272818088531494\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 4,\n'
 '      "qubit_2": 5,\n'
 '      "parameter": 0.07920926809310913\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 0\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 6.30590584478341e-05\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 3\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 0.7827677726745605\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": -0.011424980126321316\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 1,\n'
 '      "parameter": -0.5409625172615051\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": 0.347314715385437\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.0765865296125412\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 3,\n'
 '      "control_qubits": [\n'
 '        2\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": 0.793290376663208\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 0,\n'
 '      "parameter": -1.117682933807373\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 0.7761809825897217\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 2\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 3\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 4\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 5\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 0,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": -0.0028358667623251677\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 2,\n'
 '      "parameter": 1.5746475458145142\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": 0.001271416898816824\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": -0.0005387460114434361\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 0,\n'
 '      "parameter": 0.7135831713676453\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 1,\n'
 '      "parameter": 3.899910552718211e-06\n'
 '    },\n'
 '    {\n'
 '      "type": "rx",\n'
 '      "target_qubit": 2,\n'
 '      "parameter": 1.5724400281906128\n'
 '    },\n'
 '    {\n'
 '      "type": "hadamard",\n'
 '      "target_qubit": 3\n'
 '    },\n'
 '    {\n'
 '      "type": "ry",\n'
 '      "target_qubit": 4,\n'
 '      "parameter": 1.5785800218582153\n'
 '    },\n'
 '    {\n'
 '      "type": "rz",\n'
 '      "target_qubit": 5,\n'
 '      "parameter": 0.6393816471099854\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 2,\n'
 '      "control_qubits": [\n'
 '        1\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 1,\n'
 '      "qubit_2": 3,\n'
 '      "parameter": 0.19656340777873993\n'
 '    },\n'
 '    {\n'
 '      "type": "rzz",\n'
 '      "qubit_1": 2,\n'
 '      "qubit_2": 4,\n'
 '      "parameter": -0.2404092699289322\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 4,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        3\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    },\n'
 '    {\n'
 '      "type": "cx",\n'
 '      "target_qubit": 5,\n'
 '      "control_qubits": [\n'
 '        4\n'
 '      ],\n'
 '      "control_states": [\n'
 '        1\n'
 '      ]\n'
 '    }\n'
 '  ]\n'
 '}')


def build_vqe_circuit() -> Circuit:
    """重建 QAS 搜索得到的 VQE 基态线路。"""
    return circuit_from_json(VQE_CIRCUIT_JSON)
